fix: builder shortcuts visibility problem
streamsync-cloud/streamsync pull request #270
Opened 2024-02-29 10:12 UTC by raaymax

Really small but annoying thing

2024-02-29 11:06 UTC, ramedina86 requested changes

2024-02-29 11:06 UTC, ramedina86 commented on ui/src/builder/BuilderInstanceTracker.vue
> +			rendererX + rendererWidth - contentsWidth - settingsWidth,
![metricoff](https://github.com/streamsync-cloud/streamsync/assets/64783088/19da4fa9-eb8a-4060-a8f7-6235420e293c)

I tested it using our new PR review apps and yes it's problematic. You can see how far away the Shortcuts are from the selected Metric (in blue).

Please fix, reach out if you need anything. 

If you don't have access to a bigger monitor you can just stretch the window to be wider than the screen.

2024-02-29 12:12 UTC, raaymax commented on ui/src/builder/BuilderInstanceTracker.vue
> +			rendererX + rendererWidth - contentsWidth - settingsWidth,
Fixed

2024-02-29 12:16 UTC, ramedina86 commented
Tests are failing, strange, looks some invisible characters at play.

2024-03-03 18:46 UTC, ramedina86 commented
Looking good! Thanks for spotting and fixing this.

I think it's a good example of something that I got to live with without a problem but if someone else points it out, it makes total sense.

2024-03-03 18:47 UTC, merged